# Generated by Django 4.1 on 2022-08-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_affiliate_covercategory_referralcode_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cover',
            old_name='price',
            new_name='price_per_day',
        ),
        migrations.RenameField(
            model_name='referralcode',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='cover',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='covercategory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
