# Generated by Django 4.1 on 2022-08-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_price_cover_price_per_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'verbose_name': 'Cover', 'verbose_name_plural': 'Covers'},
        ),
    ]
