# Generated by Django 4.1 on 2022-08-18 13:04

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cover_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='price_per_day',
        ),
        migrations.CreateModel(
            name='CoverDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.cover')),
            ],
            options={
                'verbose_name': 'Cover Detail',
                'verbose_name_plural': 'Cover Details',
            },
        ),
    ]
