# Generated by Django 4.1 on 2022-08-18 13:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cover_countries_remove_cover_price_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Services Agreement',
                'verbose_name_plural': 'Services Agreement',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Unpaid'), (2, 'Paid')], default=1)),
                ('membership_id', models.CharField(max_length=300)),
                ('statrt_date', models.DateField()),
                ('days', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('people', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=9999)),
                ('discounted_amout', models.DecimalField(blank=True, decimal_places=2, max_digits=9999, null=True)),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.referralcode')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
    ]
