# Generated by Django 4.1 on 2022-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_servicesagreement_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='auto_revewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='email_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='services_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
