# Generated by Django 4.1 on 2022-08-18 18:54

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_statrt_date_membership_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='people',
            new_name='person',
        ),
        migrations.CreateModel(
            name='MembershipPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('emergency_contact_name', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=30)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='app.membership')),
            ],
            options={
                'verbose_name': 'Membership Person',
                'verbose_name_plural': 'Membership Persons',
            },
        ),
    ]
