# Generated by Django 4.1 on 2022-08-19 15:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_membership_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='country',
            field=django_countries.fields.CountryField(default='1', max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
