# Generated by Django 4.1 on 2022-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_country_cover_countries_cover_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipperson',
            name='membership_certificate',
            field=models.FileField(default=1, upload_to='membership_certficates'),
            preserve_default=False,
        ),
    ]
