# Generated by Django 4.1 on 2022-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_membershipperson_membership_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipperson',
            name='membership_certificate',
            field=models.FileField(null=True, upload_to='membership_certficates'),
        ),
    ]
