# Generated by Django 4.1 on 2022-08-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_membershipperson_membership_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='days_in_orange_zone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
