# Generated by Django 4.1 on 2022-08-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_membership_days_in_orange_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrangeZoneCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Orange Zone Cover',
                'verbose_name_plural': 'Orange Zone Cover',
            },
        ),
    ]
