# Generated by Django 4.1 on 2022-08-23 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_orangezonecover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covercategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orangezonecover',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
