# Generated by Django 4.1 on 2022-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_cover_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='crisis_cover',
            field=models.IntegerField(default=2),
        ),
    ]
