# Generated by Django 4.1 on 2022-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_membership_crisis_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.IntegerField(choices=[(1, 'Incomplete'), (2, 'Complete')], default=1),
        ),
    ]
