# Generated by Django 4.1 on 2022-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipperson',
            name='country_of_residence',
            field=models.CharField(max_length=100),
        ),
    ]
