# Generated by Django 4.2.2 on 2023-07-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_membershipperson_country_of_residence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
        migrations.RemoveField(
            model_name='cover',
            name='category',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='membershipperson',
            name='membership',
        ),
        migrations.DeleteModel(
            name='OrangeZoneCover',
        ),
        migrations.RemoveField(
            model_name='referralcode',
            name='affiliate',
        ),
        migrations.DeleteModel(
            name='ServicesAgreement',
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.DeleteModel(
            name='CoverCategory',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='MembershipPerson',
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
    ]
